"""add token_deny and bank_rows tables

Revision ID: b41723694a62
Revises: 0001
Create Date: 2026-05-04 19:45:08.676267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b41723694a62'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_deny',
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_table('bank_rows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('matched_ledger_id', sa.Integer(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['matched_ledger_id'], ['ledger.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matched_ledger_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_rows')
    op.drop_table('token_deny')
    # ### end Alembic commands ###
